### ISSUE TITLE
Running on Linux / docker with .NET Core: Function DATAPTR_OR_NULL not found in native library libR.so

### ISSUE THREAD

**Issue by kierenj** [rdotnet/rdotnet#103]
I'm using a Dockerfile which effectively does `apt-get install r-base` (I have `libopenblas-base` too but removing it makes no difference) then runs a .NET Core app with the latest R.NET.

As I understand it the base image is on Debian 9.

```docker
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS runner
WORKDIR /app

# install R
RUN apt-get update \
	&& apt-get -y install libopenblas-base r-base \
	&& apt-get clean
ENV R_HOME /usr/lib/R
```

The library loads fine - if I remove `/usr/lib/R/lib/libR.so`, it fails much sooner.  I see the comment in the getting starting guide, about `LD_LIBRARY_PATH`, but the error is the same if I set that to `/usr/lib/R/lib` (init works, but the call fails).

Not sure if relevant - I'm new to this - but `nm -D /usr/lib/R/lib/libR.so | grep -i data` doesn't show a function exported from `libR.so` called `DATAPTR_OR_NULL`. So maybe the error is telling the truth?

The code is based on the sample repo:

```c#
var r = REngine.GetInstance();
var charVec = r.CreateCharacterVector(new[] {"Hello, R world!, .NET speaking"});
r.SetSymbol("greetings", charVec);
r.Evaluate("str(greetings)");
var a = r.Evaluate("'Hi there .NET, from the R engine'").AsCharacter().ToArray();
```

The error:

```
Function DATAPTR_OR_NULL not found in native library libR.so

   at DynamicInterop.UnmanagedDll.throwEntryPointNotFound(String entryPoint)
      at DynamicInterop.UnmanagedDll.GetFunction[TDelegate](String entryPoint)
      at RDotNet.Vector`1.get_DataPointer()
      at RDotNet.CharacterVector.SetValue(Int32 index, String value)
      at RDotNet.CharacterVector.SetVectorDirect(String[] values)
      at RDotNet.Vector`1.SetVector(T[] values)
      at RDotNet.REngineExtension.CreateCharacterVector(REngine engine, IEnumerable`1 vector)
      at Ambilytics.Endpoints.System.RTestEndpoint.<>c.<Handle>b__0_0() in /app/Endpoints/System/RTestEndpoint.cs:line 26
      at System.Threading.Tasks.Task`1.InnerInvoke()
      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of stack trace from previous location where exception was thrown ---
      at Ambilytics.Endpoints.System.RTestEndpoint.Handle() in /app/Endpoints/System/RTestEndpoint.cs:line 23
```

**Comment by kierenj** [comment]
Is there anything I can do to help diagnose / understand the problem?

**Comment by kierenj** [comment]
For some reason, `apt-get install r-base` installs a (very) old version.

After hours of trial and error, here's something that installs 3.6.0:

```docker
# install R
RUN apt-get update \
	&& apt-get -y install gnupg2 \
	&& mkdir ~/.gnupg \
	&& echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf \
	&& apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF' \
	&& echo deb http://cloud.r-project.org/bin/linux/debian stretch-cran35/ >> /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get -y install r-base \
	&& apt-get clean
```

**Comment by lrasmus** [comment]
@kierenj - have been out of the office, but hoping to come back to this.  I'm okay to leave this open as I would definitely like to get to the bottom of what's going on (and help with documentation, if that's needed).  Thanks!

**Comment by lrasmus** [comment]
@kierenj sorry again about this issue.  "Root cause" was lack of testing on Linux on my part - I can see now that it's not able to complete the check to see if it should use the ALTREP, and defaults to assuming it should use ALTREP (https://github.com/rdotnet/rdotnet/blob/master/R.NET/REngine.cs#L278-L281).  I need to get this set up to properly determine version on Linux.  I have a test environment set up to verify once a fix is in place.

**Comment by kierenj** [comment]
In case anyone else finds it useful, there's an .NET Core runtime-with-latest-R docker image:

https://github.com/RedRiverSoftware/dockerhub/tree/master/aspnet-runtime-with-r
https://hub.docker.com/r/redriversoftware/aspnet-runtime-with-r
